// example/src/components/MSW-UI.vue
<template>
  <div>
    <h1>MSW UI</h1>
    <h2>Set global scenario</h2>
    <button @click="setScenario('success')">Success</button>
    <button @click="setScenario('fail')">Fail</button>

    <h2>Set scenario per handler</h2>
    <table>
      <thead>
        <tr>
          <th>Method</th>
          <th>Path</th>
          <th>Scenario</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="{ mask, method, header } of handlers" :key="header">
          <td>{{ method }}</td>
          <td>{{ mask }}</td>
          <td>
            <!-- <select @change="setScenarioForHandler(header, $event.target.value)">
              <option v-for="(scenario, scenarioName) of scenariosPerHandler[header]" :key="scenarioName">
                {{ scenarioName }}
              </option>
            </select> -->
            <button
              v-for="(scenario, scenarioName) of scenariosPerHandler[header]"
              :key="scenarioName"
              @click="setScenarioForHandler(header, scenarioName)"
            >
              {{ scenarioName }}
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';
import { setScenario, setScenarioForHandler } from '../../../src';
import { scenariosPerHandler } from '@/mocks';

export default defineComponent({
  name: 'Home',
  setup() {
    return {
      handlers: computed(() =>
        Object.keys(scenariosPerHandler).map(header => {
          const [method, mask] = header.split(' ');
          return { header, method, mask };
        })
      ),
      scenariosPerHandler,
      setScenario,
      setScenarioForHandler,
    };
  },
});
</script>

<style>
button {
  margin-right: 0.5rem;
}

th,
td {
  text-align: left;
  padding: 0.25rem 1rem;
}

th:first-child,
td:first-child {
  padding-left: 0;
}
</style>

// example-angular/projects/msw-ui-angular/src/lib/msw-ui.component.ts
import { Component, Inject } from '@angular/core';
import { RestHandler } from 'msw';

@Component({
  selector: 'app-msw-ui',
  templateUrl: './msw-ui.component.html',
  styles: [
    `
      button {
        margin-right: 0.5rem;
      }

      th,
      td {
        text-align: left;
        padding: 0.25rem 1rem;
      }

      th:first-child,
      td:first-child {
        padding-left: 0;
      }
    `,
  ],
})
export class MSWUIComponent {
  constructor(
    @Inject('scenarios') private scenarios: Record<string, RestHandler | RestHandler[]>,
    @Inject('setScenario') public setScenario: (scenario: string) => void
  ) {}

  get globalScenarios() {
    return Object.entries(this.scenarios)
      .filter(([_, handlers]) => Array.isArray(handlers))
      .map(scenario => scenario[0]);
  }

  get scenariosPerHandler() {
    return (Object.values(
      Object.entries(this.scenarios)
        .filter(([_, handlers]) => !Array.isArray(handlers))
        // Group by endpoint (info.header)
        // @ts-ignore
        .reduce((acc, [scenarioName, handler]: [string, RestHandler]) => {
          const key = handler.info.header;
          const [method, path] = key.split(' ');
          if (!(key in acc)) {
            acc[key] = { method, path, scenarios: [] };
          }
          acc[key].scenarios.push(scenarioName);

          return acc;
        }, {} as Record<string, { method: string; path: string; scenarios: string[] }>)
    ) as unknown) as { method: string; path: string; scenarios: string[] }[];
  }
}

<div style="width: 1000px">
  <h1>MSW UI</h1>
  <h2>Set global scenario</h2>
  <button *ngFor="let scenario of globalScenarios" (click)="setScenario(scenario)">
    {{ scenario }}
  </button>

  <h2>Set scenario per handler</h2>

  <table>
    <thead>
      <tr>
        <th>Method</th>
        <th>Path</th>
        <th>Scenario</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let endpoint of scenariosPerHandler">
        <td>{{ endpoint.method }}</td>
        <td>{{ endpoint.path }}</td>
        <td>
          <button *ngFor="let scenario of endpoint.scenarios" (click)="setScenario(scenario)">
            {{ scenario }}
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
