// src/MSW-UI.vue
<template>
  <div>
    <h1>MSW UI</h1>
    <h2>Set global scenario</h2>
    <button
      v-for="[scenario] of globalScenarios"
      @click="setScenario(scenario)"
    >
      {{ scenario }}
    </button>

    <h2>Set scenario per handler</h2>

    <table>
      <thead>
        <tr>
          <th>Method</th>
          <th>Path</th>
          <th>Scenario</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(endpoint, key) of scenariosPerHandler" :key="key">
          <td>{{ endpoint.method }}</td>
          <td>{{ endpoint.path }}</td>
          <td>
            <button
              v-for="scenario of endpoint.scenarios"
              :key="scenario"
              @click="setScenario(scenario)"
            >
              {{ scenario }}
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { RestHandler } from 'msw';
import { computed, defineComponent, PropType } from 'vue';
import { setScenario } from '.';

export default defineComponent({
  name: 'Home',
  props: {
    scenarios: {
      required: true,
      type: Object as PropType<Record<string, RestHandler>>,
    },
  },
  setup(props) {
    return {
      scenariosPerHandler: computed(() =>
        Object.entries(props.scenarios)
          .filter(([_, handlers]) => !Array.isArray(handlers))
          // Group by endpoint (info.header)
          .reduce((acc, [scenarioName, { info }]) => {
            const key = info.header;
            const [method, path] = key.split(' ');
            if (!(key in acc)) {
              acc[key] = { method, path, scenarios: [] };
            }
            acc[key].scenarios.push(scenarioName);

            return acc;
          }, {} as Record<string, { method: string; path: string; scenarios: string[] }>)
      ),
      globalScenarios: computed(() =>
        Object.entries(props.scenarios).filter(([_, handlers]) =>
          Array.isArray(handlers)
        )
      ),
      setScenario,
    };
  },
});
</script>

<style>
button {
  margin-right: 0.5rem;
}

th,
td {
  text-align: left;
  padding: 0.25rem 1rem;
}

th:first-child,
td:first-child {
  padding-left: 0;
}
</style>

// example-angular/projects/msw-ui-angular/src/lib/msw-ui.component.ts
import { Component, Inject } from '@angular/core';
import { RestHandler } from 'msw';

@Component({
  selector: 'app-msw-ui',
  templateUrl: './msw-ui.component.html',
  styles: [
    `
      button {
        margin-right: 0.5rem;
      }

      th,
      td {
        text-align: left;
        padding: 0.25rem 1rem;
      }

      th:first-child,
      td:first-child {
        padding-left: 0;
      }
    `,
  ],
})
export class MSWUIComponent {
  constructor(
    @Inject('scenarios') private scenarios: Record<string, RestHandler | RestHandler[]>,
    @Inject('setScenario') public setScenario: (scenario: string) => void
  ) {}

  get globalScenarios() {
    return Object.entries(this.scenarios)
      .filter(([_, handlers]) => Array.isArray(handlers))
      .map(scenario => scenario[0]);
  }

  get scenariosPerHandler() {
    return (Object.values(
      Object.entries(this.scenarios)
        .filter(([_, handlers]) => !Array.isArray(handlers))
        // Group by endpoint (info.header)
        // @ts-ignore
        .reduce((acc, [scenarioName, handler]: [string, RestHandler]) => {
          const key = handler.info.header;
          const [method, path] = key.split(' ');
          if (!(key in acc)) {
            acc[key] = { method, path, scenarios: [] };
          }
          acc[key].scenarios.push(scenarioName);

          return acc;
        }, {} as Record<string, { method: string; path: string; scenarios: string[] }>)
    ) as unknown) as { method: string; path: string; scenarios: string[] }[];
  }
}

<div style="width: 1000px">
  <h1>MSW UI</h1>
  <h2>Set global scenario</h2>
  <button *ngFor="let scenario of globalScenarios" (click)="setScenario(scenario)">
    {{ scenario }}
  </button>

  <h2>Set scenario per handler</h2>

  <table>
    <thead>
      <tr>
        <th>Method</th>
        <th>Path</th>
        <th>Scenario</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let endpoint of scenariosPerHandler">
        <td>{{ endpoint.method }}</td>
        <td>{{ endpoint.path }}</td>
        <td>
          <button *ngFor="let scenario of endpoint.scenarios" (click)="setScenario(scenario)">
            {{ scenario }}
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
